// use `AUTH.<name>` prefix for most cases

export const AUTH_ERROR = {
    READ_ONLY_MODE_ENABLED: 'READ_ONLY_MODE_ENABLED',
    DB_UNIQUE_VIOLATION: 'AUTH.DB.UNIQUE_VIOLATION',
    NUMERIC_VALUE_OUT_OF_RANGE: 'AUTH.DB.NUMERIC_VALUE_OUT_OF_RANGE',
    DECODE_ID_FAILED: 'AUTH.DECODE_ID_FAILED',
    VALIDATION_ERROR: 'AUTH.VALIDATION_ERROR',
    USER_ALREADY_EXISTS: 'AUTH.USER_ALREADY_EXISTS',
    NEED_RESET: 'AUTH.NEED_RESET',
};

export const READ_ONLY_MODE_CODE = 451;
